apiVersion: apps/v1
kind: Deployment
metadata:
   name: spr-mysql
   annotations:
      dependencies: "git 2.0,  jdkv8.0, springboot"
      on-call: "Shwetha Cell:7829181823 email: guptha.shwetha@gmail.com"
   labels:
      type: back-end
spec:
    replicas: 4
    selector:
      matchLabels:
        type: back-end
    template:
      metadata:
        name: spr-mysql
        annotations:
          dependencies: "git 2.0,  jdkv8.0, springboot"
          on-call: "Shwetha Cell:7829181823 email: guptha.shwetha@gmail.com"
        labels:
          type: back-end
      spec:
        containers:
          - name: sp-com
            image: shwetha313/spring-new-code
            ports:
               - name: sp-com
                 containerPort: 8080

---
 # Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: spr-mysql
  name: spr-mysql
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    name: spr-mysql
---
# mysql host
apiVersion: apps/v1
kind: Deployment
metadata:
   name: my-db
   labels:
      type: db
spec:
    replicas: 1 
    selector:
      matchLabels:
        type: db
    template:
      metadata:
        name: my-db
        labels:
          type: db
      spec:
        containers:
        - image: mysql
          name: my-db
          ports:
          - name: my-db
            containerPort: 3306
            hostPort: 3306
          volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /data/db
        volumes:
          - name: mysql-persistent-storage
            hostPath:
              path: /tmp/dbbackup         
---
# mysql node port
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: mysql
  name: mysql
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql
    name: mysql
    tier: mysql          
                            